linters:
  # default: errcheck gosimple govet ineffassign staticcheck typecheck unused
  enable:
    - gocyclo
    # - gofmt # spurious errors on github actions windows-latest...
    - gosec
    - misspell
    - stylecheck
    - whitespace
