#+TITLE: New Aeon English Qabalah CLI

Inspired by https://www.naeq.io/ & http://www.naequery.com/

#+begin_src txt
Usage: naeq [options...] <words to process>:
  -n int
        number of matches to show
  -p string
        path to alternative book
#+end_src

* Gematria and Qabalah

Hermetic Qabalah is a derivative of a school of Jewish mysticism called
Kabbalah that was developed by modern Western esotericists as a way to explore
the divine and the nature of the universe. One aspect of Qabalah is Gematria, a
mystical interpretation of a holy text using specific mathematical laws. A
Gematria is a system used to assign a numeric value for each letter of a word,
which is then summed. This sum can be referred to as the “key” of that word, or
phrase. Words and phrases that have the same numeric value are thought to have
similar properties and can be used to meditate on hidden meanings or
relationships contained within those similarities.

* The Book of The Law

The Book of the Law — or Liber AL vel Legis — is the central holy text of
Thelema, a spiritual and social philosophy derived from Western esotericism and
founded by magician Aleister Crowley. Liber AL vel Legis was dictated to
Crowley over the course of three days in 1904 by a discarnate entity called
Aiwass.

* The New Aeon English Qabalah

Since Hebrew Gematria uses the Hebrew script to derive values, it does not
neccessarily apply as well to English or Roman scripts and thus efforts have
been made over the years to develop an “English Qabalah” that could be utilized
with texts in those languages.

In Chapter II verse 55 of Liber AL vel Legis, Crowley writes: “Thou shalt
obtain the order & value of the English Alphabet, thou shalt find new symbols
to attribute them unto”. When analyzing this information later, Crowley
realized that this implied there was a cipher contained within Liber AL that
had yet to be discovered or developed. Later on, in Chapter III sheet 16 of the
original documents, there is a unique page that contains a grid of numbers, a
slash through it, and a circle within a cross.

This page in particular is where the ALW cipher, or New Aeon English Qabalah,
is derived. James Lees discovered in 1976 that this key was based on the
magical number 11. By taking every eleventh letter of the alphabet as the
order, and then assigning them sequential values you are able to arrive at this
cipher:

#+begin_src text
A=1 L=2 W=3 H=4 S=5 D=6 O=7 Z=8 K=9 V=10 G=11 R=12 C=13 N=14 Y=15 J=16 U=17 F=18 Q=19 B=20 M=21 X=22 I=23 T=24 E=25 P=26
#+end_src

* The Secret Cipher of the UFOnauts

Secret Cipher of the UFOnauts, a book published in 1994 and written by
occultist and ufologist Allen H. Greenfield seeks to help elucidate the nature
of the mysterious Aiwass that dictated Liber AL to Crowley, and the myriad
entities encountered by UFO contactees in the 20th and 21st century. His theory
was that ultraterrestrials - a term used by researcher and author John Keel
used to describe the beings - transmitted information to humans in a secret,
enciphered format, in the guise of enlightened messages. These entities often
used authors to produce voluminous works, such as Jane Roberts' “Seth” and the
“Ephraim” that communicated with poet James Merrill during his writing of The
Changing Light at Sandover. In particular, Greenfield conjectures that Liber AL
was the ultimate key to this secret cipher utilized by the ultraterrestrials.

Greenfield believed that by utilizing the ALW cipher/NAEQ you could take the
names of these entities, or information they provided and compare their cipher
value using the values of phrases or words from Liber AL as a key. By analyzing
words or phrases in Liber AL that had the same values, one could arrive at
further insight, or obtain major revelations about the nature of these entities
or their motivations.
