name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-go@v3
      - name: Build
        run: go build -v ./...
      - name: Vet
        run: go vet -v ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v3
      - name: Test
        run: |
          go test -v ./... -covermode=count -coverprofile=c.out
          go tool cover -func=c.out
