on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

name: Release

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # https://github.com/actions/upload-release-asset/issues/28#issuecomment-617208601
    # https://github.com/github/hub
    - name: Release
      run: |
        make all
        assets=()
        for asset in ./alw-*-*-*; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
