on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  # workflow_run:
  #   workflows: ["Build"]
  #   branches: [main]
  #   types:
  #     - completed

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make all
    # https://github.com/actions/upload-release-asset/issues/28#issuecomment-617208601
    # https://github.com/github/hub
    - name: Release
      run: |
        assets=()
        for asset in ./alw-*-*-*; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Clean
      run: make clean
